# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_usuario', models.CharField(max_length=20)),
                ('no_usuario', models.CharField(blank=True, default='', max_length=50)),
                ('ds_senha', models.CharField(blank=True, default='', max_length=14)),
                ('co_usuario_autorizacao', models.CharField(blank=True, max_length=20, null=True)),
                ('nu_matricula', models.BigIntegerField(blank=True, null=True)),
                ('dt_nascimento', models.DateField(blank=True, null=True)),
                ('dt_admissao_empresa', models.DateField(blank=True, null=True)),
                ('dt_desligamento', models.DateField(blank=True, null=True)),
                ('dt_inclusao', models.DateTimeField(blank=True, null=True)),
                ('dt_expiracao', models.DateField(blank=True, null=True)),
                ('nu_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('nu_rg', models.CharField(blank=True, max_length=20, null=True)),
                ('no_orgao_emissor', models.CharField(blank=True, max_length=10, null=True)),
                ('uf_orgao_emissor', models.CharField(blank=True, max_length=2, null=True)),
                ('ds_endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('no_email', models.CharField(blank=True, max_length=100, null=True)),
                ('no_email_pessoal', models.CharField(blank=True, max_length=100, null=True)),
                ('nu_telefone', models.CharField(blank=True, max_length=64, null=True)),
                ('dt_alteracao', models.DateField(blank=True, null=True)),
                ('url_foto', models.TextField(blank=True, null=True)),
                ('instant_messenger', models.CharField(blank=True, max_length=80, null=True)),
                ('icq', models.PositiveIntegerField(null=True)),
                ('msn', models.CharField(blank=True, max_length=50, null=True)),
                ('yms', models.CharField(blank=True, max_length=50, null=True)),
                ('ds_comp_end', models.CharField(blank=True, max_length=50, null=True)),
                ('ds_bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('nu_cep', models.CharField(blank=True, max_length=10, null=True)),
                ('no_cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('uf_cidade', models.CharField(blank=True, max_length=2, null=True)),
                ('dt_expedicao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='caousuario',
            unique_together=set([('co_usuario', 'no_usuario', 'dt_alteracao')]),
        ),
    ]
