# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caousuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='caousuario',
            name='co_usuario',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
