# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0003_auto_20171108_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaoOs',
            fields=[
                ('co_os', models.IntegerField(primary_key=True, serialize=False)),
                ('nu_os', models.IntegerField(null=True)),
                ('co_sistema', models.IntegerField(default=0)),
                ('co_usuario', models.CharField(default='0', max_length=50)),
                ('co_arquitetura', models.IntegerField(default=0)),
                ('ds_os', models.CharField(default='0', max_length=200)),
                ('ds_caracteristica', models.CharField(default='0', max_length=200)),
                ('ds_requisito', models.CharField(blank=True, max_length=200, null=True)),
                ('dt_inicio', models.DateField(blank=True, null=True)),
                ('dt_fim', models.DateField(blank=True, null=True)),
                ('co_status', models.IntegerField(default=0)),
                ('diretoria_sol', models.CharField(default='0', max_length=50)),
                ('dt_sol', models.DateField(blank=True, null=True)),
                ('nu_tel_sol', models.CharField(default='0', max_length=20)),
                ('ddd_tel_sol', models.CharField(blank=True, max_length=5, null=True)),
                ('nu_tel_sol2', models.CharField(blank=True, max_length=20, null=True)),
                ('ddd_tel_sol2', models.CharField(blank=True, max_length=5, null=True)),
                ('usuario_sol', models.CharField(default='0', max_length=50)),
                ('dt_imp', models.DateField(blank=True, null=True)),
                ('dt_garantia', models.DateField(blank=True, null=True)),
                ('co_email', models.IntegerField(null=True)),
                ('co_os_prospect_rel', models.IntegerField(null=True)),
            ],
        ),
    ]
