# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0004_caoos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaoFatura',
            fields=[
                ('co_fatura', models.IntegerField(primary_key=True, serialize=False)),
                ('co_cliente', models.IntegerField(default=0)),
                ('co_sistema', models.IntegerField(default=0)),
                ('co_os', models.IntegerField(default=0)),
                ('num_nf', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('valor', models.FloatField(default=0)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('corpo_nf', models.TextField()),
                ('comissao_cn', models.FloatField(default=0)),
                ('total_imp_inc', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CaoSalario',
            fields=[
                ('co_usuario', models.CharField(blank=True, default='', max_length=20, primary_key=True, serialize=False)),
                ('dt_alteracao', models.DateField(blank=True, null=True)),
                ('brut_salario', models.FloatField(default=0)),
                ('liq_salario', models.FloatField(default=0)),
            ],
        ),
    ]
