# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-23 13:00
from __future__ import unicode_literals
from django.db import migrations
import os
import json
FOLDER_ROOT = os.path.dirname(os.path.abspath(__file__))
from django.db import connection
from django.conf import settings


def load_data(apps, schema_editor):
    if settings.TEST is True:
        return

    with connection.cursor() as cursor:
        csv = "load_data/cao_fatura.csv"
        file_dir = os.path.join(FOLDER_ROOT, csv)

        sql_query = """
        COPY desempenho_caofatura FROM '%s'
        DELIMITER ',' QUOTE '|' CSV
        """ % file_dir

        cursor.execute(sql_query)


class Migration(migrations.Migration):
    dependencies = [
        ('desempenho', '0005_caofatura_caosalario'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
