# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-23 13:00
from __future__ import unicode_literals
from django.db import migrations, models
import os
import json
FOLDER_ROOT = os.path.dirname(os.path.abspath(__file__))
from django.db import connection
from django.conf import settings


def load_data(apps, schema_editor):
    if settings.TEST or settings.HEROKU is True:
        return

    with connection.cursor() as cursor:

        sql_query = """
        COPY desempenho_caoos FROM '%s'
        DELIMITER ',' QUOTE '"' ESCAPE '\\' NULL '\\N' CSV
        """ % get_filename("cao_os")
        cursor.execute(sql_query)

        sql_query = """
        COPY desempenho_caousuario FROM '%s'
        DELIMITER ',' QUOTE '"' ESCAPE '\\' NULL '\\N' CSV
        """ % get_filename("cao_usuario")
        cursor.execute(sql_query)

        sql_query = """
        COPY desempenho_caosalario FROM '%s'
        DELIMITER ',' QUOTE '"' ESCAPE '\\' NULL '\\N' CSV
        """ % get_filename("cao_salario")
        cursor.execute(sql_query)

        fields = "(co_usuario,co_tipo_usuario,co_sistema," \
                 "in_ativo,co_usuario_atualizacao,dt_atualizacao)"

        sql_query = """
        COPY desempenho_permissaosistema %s FROM '%s'
        DELIMITER ',' QUOTE '"' ESCAPE '\\' NULL '\\N' CSV
        """ % (fields, get_filename("permissao_sistema"))
        cursor.execute(sql_query)



def get_filename(name):
    csv = "load_data/{}.csv".format(name)
    file_dir = os.path.join(FOLDER_ROOT, csv)
    return file_dir


class Migration(migrations.Migration):
    dependencies = [
        ('desempenho', '0006_load_data_cao_fatura'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
