# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-23 13:00
from __future__ import unicode_literals
from django.db import migrations, models
import os
import json
FOLDER_ROOT = os.path.dirname(os.path.abspath(__file__))
from django.conf import settings
from django.contrib.auth.models import User


def create_user(apps, schema_editor):
    if settings.TEST is True:
        return

    User.objects.create_superuser(username='agence', password='agence1o1',
                                  email='agence@mail.com')




class Migration(migrations.Migration):
    dependencies = [
        ('desempenho', '0007_load_data'),
    ]

    operations = [
        migrations.RunPython(create_user),
    ]
