# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0008_create_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissaosistema',
            name='co_usuario',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='permissaosistema',
            name='in_ativo',
            field=models.CharField(choices=[('S', 'Inactivo')], default='S', max_length=1),
        ),
    ]
