# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.db import connection


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0009_auto_20171110_2048'),
    ]

    def sanity_data(apps, schema_editor):
        with connection.cursor() as cursor:
            sql_query = """
            DELETE FROM desempenho_permissaosistema 
              WHERE co_usuario NOT IN (SELECT u.co_usuario 
                                          FROM desempenho_caousuario u)
            """
            cursor.execute(sql_query)

    operations = [
        migrations.RunPython(sanity_data),
        migrations.AlterField(
            model_name='permissaosistema',
            name='co_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desempenho.CaoUsuario'),
        ),
    ]
