# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0010_auto_20171110_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissaosistema',
            name='co_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='desempenho.CaoUsuario'),
        ),
    ]
